// packages/vue-with-webcomponent/src/App.vue
<template>
    <ul class="list-group">
      <li>
        Vue counter
        <span class="badge">{{ count }}</span>
      </li>
      <li>
        <my-counter
          :title="myTitle"
          v-on:click="handleClick"
          @customOnClick="handleCustomClick"
        ></my-counter>
      </li>
    </ul>
</template>

<script>
import "MyCounter";
import "./App.css";

export default {
  name: "App",
  data() {
    return {
      count: 0,
      myTitle: `咣`,
    };
  },
  methods: {
    handleClick: function (event) {
      console.log(event);
    },
    handleCustomClick: function (event) {
      this.count++;
      console.log(event.detail.text);
    },
  },
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// react-with-webcomponent/src/App.js
import React, { useState, useEffect, useRef } from "react";
import "MyCounter";
import './App.css';
 
function App() {
  const [count, setCount] = useState(0);
  const buttonRef = useRef();
  // console.log(buttonRef)
  useEffect(() => {
    buttonRef.current.addEventListener("customOnClick", (e) => {
      setCount(count + 1)
      console.log(e.detail.text)
    });
  });
  return (
    <div>
      <ul className="list-group">
        <li>React counter
            <span className="badge">{count}</span>
        </li>
        <li>        
          <my-counter
            name="+"
            title="咣"
            ref={buttonRef}
            // the classic onClick also works
            onClick={(e) => {
              console.log("on click", e);
            }}
          />
        </li>
      </ul>
    </div>
  );
}
 
export default App;
