// packages/react-with-webcomponent/src/App.js
import React, { useState, useEffect, useRef } from "react";
import "MyCounter";
import './App.css';
 
function App() {
  const [count, setCount] = useState(0);
  const buttonRef = useRef();
  // console.log(buttonRef)
  useEffect(() => {
    let curRef = buttonRef.current
    
    function handleClick (e) {
      setCount(count + 1)
      console.log(e.detail.text)      
    }
    
    if (buttonRef && buttonRef.current) {
      curRef.addEventListener("customOnClick", handleClick)
    }
    
    return () => {
      curRef.removeEventListener("customOnClick", handleClick)
    }
  });
  return (
    <div>
      <ul className="list-group">
        <li>React counter
            <span className="badge">{count}</span>
        </li>
        <li>        
          <my-counter
            name="+"
            title="当"
            ref={buttonRef}
            // the classic onClick also works
            onClick={(e) => {
              console.log("on click", e);
            }}
          />
        </li>
      </ul>
    </div>
  );
}
 
export default App;

// packages/vue3-with-webcomponent/src/App.vue
<script>
import HelloWorld from './components/HelloWorld.vue'
import "MyCounter";
import "./App.css";

export default {
  name: "App",
  data() {
    return {
      count: 0,
      myTitle: `咣`,
    };
  },
  methods: {
    handleClick: function (event) {
      console.log(event);
    },
    handleCustomClick: function (event) {
      this.count++;
      console.log(event.detail.text);
    },
  },
};
</script>

<template>
  <main>
    <ul class="list-group">
      <li>
        Vue counter
        <span class="badge">{{ count }}</span>
      </li>
      <li>
        <my-counter
          :title="myTitle"
          v-on:click="handleClick"
          @customOnClick="handleCustomClick"
        ></my-counter>
      </li>
    </ul>
  </main>
</template>

<style scoped>
header {
  line-height: 1.5;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }
}
</style>
